TYPO3:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          'TYPO3\Media\Domain\EventListener\ImageEventListener':
            events: ['postRemove']
            listener: 'TYPO3\Media\Domain\EventListener\ImageEventListener'
  Media:
    # This setting simulates how Neos 1.2 handled image cropping with "maximumWidth" and "maximumHeight".
    # This behaviour is deprecated and will be removed in Neos 3.0, "maximumWidth" and "maximumHeight"
    # need to be replaced by "width" and "height" if you need fixed dimensions.
    behaviourFlag: '1.2'
    asset:
      modelMappingStrategy:
        default: TYPO3\Media\Domain\Model\Document
        patterns:
          '[image/.*]':
            className: TYPO3\Media\Domain\Model\Image
          '[audio/.*]':
            className: TYPO3\Media\Domain\Model\Audio
          '[video/.*]':
            className: TYPO3\Media\Domain\Model\Video
    image:
      defaultOptions:
        # Image quality, from 0 to 100
        'quality': 90
